
import { type NextPage } from "next";
import Head from "next/head";
import { api } from "~/utils/api";
import CustomerOrder from "~/components/CustomerOrder";
import React from "react";
import { useRouter } from "next/router";


interface Item {
  price: number;
}



const NewOrder: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });
  const router = useRouter();
  const { basket } = router.query;
  const basketData: Item[] = [];

  return (
    <>
      <Head>
        <title>Restaurant Istanbul Till</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CustomerOrder basket={basketData} />
    </>
  );
};

export default NewOrder;