import { type NextPage } from "next";
import Head from "next/head";

import Drinks from "~/components/menu/Drinks/Drinks";

const OldCustomer: NextPage = () => {


  return (
    <>
      <Head>
      <title>Restaurant Istanbul Till</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Drinks />
    </>
  );
};

export default OldCustomer;















