import { type NextPage } from "next";
import Head from "next/head";

import Starters from "~/components/menu/Starters/Starters";


const OldCustomer: NextPage = () => {


  return (
    <>
      <Head>
      <title>Restaurant Istanbul Till</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Starters />
    </>
  );
};

export default OldCustomer;
